### ISSUE TITLE
Nox Emulator not loading after Magisk is installed.

### ISSUE THREAD

**Issue by IvesAwadi** [HuskyDG/MagiskOnNox#1]
![](https://i.imgur.com/dTdEJin.png)
- After installing Magisk, ticking off the root checkbox, the emulator doesn't load anymore. Stuck in a boot loop pretty much.
- Any fixes/recommendations?

**Comment by HuskyDG** [comment]
What is Android version of Nox?
Example: Android 9 64-bit

**Comment by IvesAwadi** [comment]
> What is Android version of Nox? Example: Android 9 64-bit

Android 7 (64bit)

**Comment by HuskyDG** [comment]
Currently it is only works on Android 9 Nox.
Luckily I just discover this problem yesterday, pleased try this build https://github.com/HuskyDG/MagiskOnNox/releases/tag/v1.1

**Comment by HuskyDG** [comment]
Also use Magisk.apk version 22.0

**Comment by HuskyDG** [comment]
Confirmed! It's works.
https://github.com/HuskyDG/MagiskOnNox/releases/download/v1.1/magisk-on-nox_android_7_64.zip
