### ISSUE TITLE
Stable version for Memu?

### ISSUE THREAD

**Issue by AndnixSH** [HuskyDG/MagiskOnNox#10]
If i try canary or alpha, it bricks Memu emulator and gets stuck on 99%. Requires reinstall to unbrick again
Can you add stable version for Memu 7.1 in the app?

**Comment by HuskyDG** [comment]
For MEmu, only version Canary 23001, Stable v23 and before will work
You can try the Magisk version Canary v23001

**Comment by AndnixSH** [comment]
There is no option to download stable version

![image](https://user-images.githubusercontent.com/40742924/148421028-9c2b3989-4df3-485e-b721-2b270df73b72.png)

However, I downloaded from official repo and choosed option 5 but still bricks, now with an error

![image](https://user-images.githubusercontent.com/40742924/148421117-7f6df4fa-133e-42b7-b7fd-1dab71c1bea5.png)

**Comment by HuskyDG** [comment]
> There is no option to download stable version
> 
> ![image](https://user-images.githubusercontent.com/40742924/148421028-9c2b3989-4df3-485e-b721-2b270df73b72.png)
> 
> However, I downloaded from official repo and choosed option 5 but still bricks, now with an error
> 
> ![image](https://user-images.githubusercontent.com/40742924/148421117-7f6df4fa-133e-42b7-b7fd-1dab71c1bea5.png)

Yes, you are right, it got bootloop
I noticed about the problem with the script

**Comment by HuskyDG** [comment]
> There is no option to download stable version
> 
> ![image](https://user-images.githubusercontent.com/40742924/148421028-9c2b3989-4df3-485e-b721-2b270df73b72.png)
> 
> However, I downloaded from official repo and choosed option 5 but still bricks, now with an error
> 
> ![image](https://user-images.githubusercontent.com/40742924/148421117-7f6df4fa-133e-42b7-b7fd-1dab71c1bea5.png)

Fixed in https://github.com/HuskyDG/MagiskOnNox/commit/ed7686891735c72ca92a6695ef3ab28e918738e0#diff-eccb6674629487f16a0a39168879ac7b1babf2a779d510cbf66757bfdb41a34e

**Comment by AndnixSH** [comment]
Thanks, it works now!
