### ISSUE TITLE
Nox Android 9 [!] Installation Failed after picking a file during module installation.

### ISSUE THREAD

**Issue by orariley70** [HuskyDG/MagiskOnNox#13]
After picking a file, Magisk Module installation will always fail, no matter the file picker.

**Comment by HuskyDG** [comment]
Which version of my MagiskOnNox script?

**Comment by HuskyDG** [comment]
Which version of my MagiskOnNox script?
And Magisk version?
Make sure you have made **Additional Setup** when Magisk app asked for doing that

**Comment by orariley70** [comment]
v13.2(10030)
Magisk did not ask for additional setup

**Comment by HuskyDG** [comment]
> v13.2(10030) Magisk did not ask for additional setup

So what is Magisk version?

**Comment by orariley70** [comment]
Stable (23)
Fox MMM doesn't work too, (your file picker failed or something like that)

**Comment by HuskyDG** [comment]
> Stable (23) Fox MMM doesn't work too, (your file picker failed or something like that)

Have you read my wiki?? 😌 Please use lastest Canary or Alpha

**Comment by HuskyDG** [comment]
Magisk Stable v23 on Android 9 Nox Player has a bug that cannot install Magisk module. Please use Magisk Canary / Alpha version instead

**Comment by orariley70** [comment]
i feel so dumb… sorry. I thought stable would work.
