### ISSUE TITLE
Please add support for 32 bit emulators like Bluestacks!

### ISSUE THREAD

**Issue by david8557** [HuskyDG/MagiskOnNox#2]
Hi, you did a great job on adding Magisk for emulators. I wonder If you could please add support for 32 bit emulators like Bluestacks! Thank you very much!

**Comment by HuskyDG** [comment]
Thanks for suggestion, I will do this soon...! Keep looking forward!

**Comment by HuskyDG** [comment]
Add support for 32bit emulator, try this build.
https://github.com/HuskyDG/MagiskOnNox/releases/tag/v1.9

If you have any problem, please open new issue!
